services:
  app:
    image: ctxai_cluster:latest
    build: .
    ports:
      - "8984:8984"
    environment:
      - FLASK_ENV=production
    expose:
      - 8984
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ipc: host
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: gunicorn --bind 0.0.0.0:8984 --threads=12 wsgi:app  # --certfile=utils/cert.pem --keyfile=utils/key.pem
